### ISSUE TITLE
SQL search sometimes fails with an error window

### ISSUE THREAD

**Issue by brunogautier** [christophefondacci/nextep-designer#14]
When searching through the SQL code using the "SQL search" functionality (Shortcut CTRL+H / "SQL search" tab), an error window sometimes pops up with the message `An internal error occurred during: "Looking for '...' SQL references..."`.

The following stacktrace is logged:
```
!STACK 0
java.lang.NullPointerException
	at com.nextep.designer.sqlgen.ui.impl.SQLSearchQuery.run(SQLSearchQuery.java:101)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by brunogautier** [comment]
The problem appears to occur systematically in an Oracle workspace with user types that do not have a body.
